<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Identity.Application\Identity.Application.csproj" />
      <ProjectReference Include="..\Identity.Persistence\Identity.Persistence.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="MassTransit.Abstractions">
        <HintPath>..\..\..\..\..\..\.nuget\packages\masstransit.abstractions\9.1.0\lib\net10.0\MassTransit.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
