// <auto-generated />
using System;
using System.Collections.Generic;
using Lending.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lending.Persistence.Migrations
{
    [DbContext(typeof(LendingDbContext))]
    [Migration("20260404214214_LenderIdColumnOnLoans")]
    partial class LenderIdColumnOnLoans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lending.Domain.Loans.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(10);

                    b.Property<DateTimeOffset?>("DisbursedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disbursed_at")
                        .HasColumnOrder(11);

                    b.Property<Guid>("LenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("lender_id")
                        .HasColumnOrder(15);

                    b.Property<DateOnly?>("OneTimeDueDate")
                        .HasColumnType("date")
                        .HasColumnName("one_time_due_date")
                        .HasColumnOrder(13);

                    b.Property<string>("PaymentFrequency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("payment_frequency")
                        .HasColumnOrder(9);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status")
                        .HasColumnOrder(14);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "InterestRate", "Lending.Domain.Loans.Loan.InterestRate#InterestRate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Period")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("rate_period")
                                .HasColumnOrder(5);

                            b1.Property<decimal>("Rate")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("interest_rate")
                                .HasColumnOrder(4);
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OneTimeInterest", "Lending.Domain.Loans.Loan.OneTimeInterest#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("one_time_interest")
                                .HasColumnOrder(12);
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PenaltyInterestRate", "Lending.Domain.Loans.Loan.PenaltyInterestRate#InterestRate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Period")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("penalty_rate_period")
                                .HasColumnOrder(7);

                            b1.Property<decimal>("Rate")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("penalty_interest_rate")
                                .HasColumnOrder(6);
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Principal", "Lending.Domain.Loans.Loan.Principal#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("principal")
                                .HasColumnOrder(3);

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency")
                                .HasColumnOrder(2);
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Term", "Lending.Domain.Loans.Loan.Term#Term", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("term")
                                .HasColumnOrder(8);
                        });

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DisbursedAt")
                        .HasFilter("disbursed_at IS NOT NULL");

                    b.HasIndex("ClientId", "CreatedAt");

                    b.ToTable("loans", "lending", t =>
                        {
                            t.HasCheckConstraint("ck_loans_disbursed_after_created", "disbursed_at IS NULL OR disbursed_at >= created_at");

                            t.HasCheckConstraint("ck_loans_interest_rate_non_negative", "interest_rate >= 0 AND interest_rate < 1");

                            t.HasCheckConstraint("ck_loans_one_time_due_date_after_created", "one_time_due_date IS NULL OR one_time_due_date >= created_at");

                            t.HasCheckConstraint("ck_loans_one_time_interest_non_negative", "one_time_interest IS NULL OR one_time_interest >= 0");

                            t.HasCheckConstraint("ck_loans_payment_frequency_valid", "payment_frequency IN ('Daily','Weekly','BiWeekly','Monthly','OneTime')");

                            t.HasCheckConstraint("ck_loans_penalty_interest_rate_positive", "penalty_interest_rate > 0 AND penalty_interest_rate < 1");

                            t.HasCheckConstraint("ck_loans_penalty_rate_period_valid", "penalty_rate_period IN ('Weekly','Monthly','Annual')");

                            t.HasCheckConstraint("ck_loans_principal_positive", "principal > 0");

                            t.HasCheckConstraint("ck_loans_rate_period_valid", "rate_period IN ('Weekly','Monthly','Annual')");

                            t.HasCheckConstraint("ck_loans_status_valid", "status IN ('Draft','Active','PaidOff')");

                            t.HasCheckConstraint("ck_loans_term_positive", "term > 0");
                        });
                });

            modelBuilder.Entity("Lending.Domain.Loans.Loan", b =>
                {
                    b.OwnsMany("Lending.Domain.Loans.Installments.Installment", "Installments", b1 =>
                        {
                            b1.Property<Guid>("LoanId")
                                .HasColumnType("uuid")
                                .HasColumnName("loan_id")
                                .HasColumnOrder(0);

                            b1.Property<int>("Number")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("number")
                                .HasColumnOrder(1);

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Number"));

                            b1.Property<DateOnly>("DueDate")
                                .HasColumnType("date")
                                .HasColumnName("due_date")
                                .HasColumnOrder(2);

                            b1.HasKey("LoanId", "Number");

                            b1.HasIndex("LoanId", "DueDate");

                            b1.ToTable("installments", "lending", t =>
                                {
                                    t.HasCheckConstraint("ck_installments_amount_paid_lte_amount", "amount_paid <= amount");

                                    t.HasCheckConstraint("ck_installments_amount_paid_non_negative", "amount_paid >= 0");

                                    t.HasCheckConstraint("ck_installments_amount_positive", "amount > 0");

                                    t.HasCheckConstraint("ck_installments_interest_non_negative", "interest >= 0");

                                    t.HasCheckConstraint("ck_installments_number_positive", "number > 0");

                                    t.HasCheckConstraint("ck_installments_principal_non_negative", "principal >= 0");
                                });

                            b1.WithOwner()
                                .HasForeignKey("LoanId");

                            b1.OwnsOne("Blocks.Domain.ValueObjects.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("InstallmentLoanId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("InstallmentNumber")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("amount")
                                        .HasColumnOrder(4);

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("currency")
                                        .HasColumnOrder(3);

                                    b2.HasKey("InstallmentLoanId", "InstallmentNumber");

                                    b2.ToTable("installments", "lending");

                                    b2.WithOwner()
                                        .HasForeignKey("InstallmentLoanId", "InstallmentNumber");
                                });

                            b1.OwnsOne("Blocks.Domain.ValueObjects.Money", "AmountPaid", b2 =>
                                {
                                    b2.Property<Guid>("InstallmentLoanId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("InstallmentNumber")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .ValueGeneratedOnAdd()
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasDefaultValue(0m)
                                        .HasColumnName("amount_paid")
                                        .HasColumnOrder(7);

                                    b2.HasKey("InstallmentLoanId", "InstallmentNumber");

                                    b2.ToTable("installments", "lending");

                                    b2.WithOwner()
                                        .HasForeignKey("InstallmentLoanId", "InstallmentNumber");
                                });

                            b1.OwnsOne("Blocks.Domain.ValueObjects.Money", "Interest", b2 =>
                                {
                                    b2.Property<Guid>("InstallmentLoanId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("InstallmentNumber")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("interest")
                                        .HasColumnOrder(6);

                                    b2.HasKey("InstallmentLoanId", "InstallmentNumber");

                                    b2.ToTable("installments", "lending");

                                    b2.WithOwner()
                                        .HasForeignKey("InstallmentLoanId", "InstallmentNumber");
                                });

                            b1.OwnsOne("Blocks.Domain.ValueObjects.Money", "Principal", b2 =>
                                {
                                    b2.Property<Guid>("InstallmentLoanId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("InstallmentNumber")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("principal")
                                        .HasColumnOrder(5);

                                    b2.HasKey("InstallmentLoanId", "InstallmentNumber");

                                    b2.ToTable("installments", "lending");

                                    b2.WithOwner()
                                        .HasForeignKey("InstallmentLoanId", "InstallmentNumber");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();

                            b1.Navigation("AmountPaid")
                                .IsRequired();

                            b1.Navigation("Interest")
                                .IsRequired();

                            b1.Navigation("Principal")
                                .IsRequired();
                        });

                    b.OwnsMany("Lending.Domain.Loans.Penalties.Penalty", "Penalties", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id")
                                .HasColumnOrder(1);

                            b1.Property<DateOnly>("AppliedAt")
                                .HasColumnType("date")
                                .HasColumnName("applied_at")
                                .HasColumnOrder(3);

                            b1.Property<int>("InstallmentNumber")
                                .HasColumnType("integer")
                                .HasColumnName("installment_number")
                                .HasColumnOrder(2);

                            b1.Property<DateOnly>("LastAppliedAt")
                                .HasColumnType("date")
                                .HasColumnName("last_applied_at")
                                .HasColumnOrder(4);

                            b1.Property<Guid>("LoanId")
                                .HasColumnType("uuid")
                                .HasColumnName("loan_id")
                                .HasColumnOrder(0);

                            b1.HasKey("Id");

                            b1.HasIndex("AppliedAt");

                            b1.HasIndex("InstallmentNumber");

                            b1.HasIndex("LoanId");

                            b1.ToTable("penalties", "lending", t =>
                                {
                                    t.HasCheckConstraint("ck_penalties_amount_paid_non_negative", "amount_paid >= 0");

                                    t.HasCheckConstraint("ck_penalties_amount_positive", "amount > 0");

                                    t.HasCheckConstraint("ck_penalties_installment_number_positive", "installment_number > 0");

                                    t.HasCheckConstraint("ck_penalties_no_overpayment", "amount_paid <= amount");
                                });

                            b1.WithOwner()
                                .HasForeignKey("LoanId");

                            b1.OwnsOne("Blocks.Domain.ValueObjects.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("PenaltyId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("amount")
                                        .HasColumnOrder(6);

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("currency")
                                        .HasColumnOrder(5);

                                    b2.HasKey("PenaltyId");

                                    b2.ToTable("penalties", "lending");

                                    b2.WithOwner()
                                        .HasForeignKey("PenaltyId");
                                });

                            b1.OwnsOne("Blocks.Domain.ValueObjects.Money", "AmountPaid", b2 =>
                                {
                                    b2.Property<Guid>("PenaltyId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .ValueGeneratedOnAdd()
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasDefaultValue(0m)
                                        .HasColumnName("amount_paid")
                                        .HasColumnOrder(7);

                                    b2.HasKey("PenaltyId");

                                    b2.ToTable("penalties", "lending");

                                    b2.WithOwner()
                                        .HasForeignKey("PenaltyId");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();

                            b1.Navigation("AmountPaid")
                                .IsRequired();
                        });

                    b.Navigation("Installments");

                    b.Navigation("Penalties");
                });
#pragma warning restore 612, 618
        }
    }
}
